#include <SFML/Graphics.h>
#include "header.h"

sfFloatRect	frect = {0, 0, 1280, 960};

const sfColor	channelColors[16] = {
	{255, 0  , 0  , 255},
	{0  , 0  , 255, 255},
	{0  , 255, 0  , 255},
	{255, 255, 0  , 255},
	{255, 0  , 255, 255},
	{0  , 255, 255, 255},
	{100, 100, 100, 255},
	{255, 120, 0  , 255},
	{255, 120, 120, 255},
	{120, 0  , 255, 255},
	{0  , 80 , 80 , 255},
	{0  , 0  , 120, 255},
	{120, 120, 255, 255},
	{120, 255, 120, 255},
	{116, 26 , 26 , 255},
	{200, 200, 200, 255},
};

const Sprite_config	configs[] = {
	{"assets/folder.png", "folder"},
	{"assets/midiFile.png", ".mid"},
	{"assets/midiFile.png", ".midi"},
	{"assets/imageFile.png", ".png"},
	{"assets/imageFile.png", ".jpg"},
	{"assets/imageFile.png", ".jpeg"},
	{"assets/imageFile.png", ".bmp"},
	{"assets/imageFile.png", ".gif"},
	{"assets/textFile.png", ".txt"},
	{"assets/textFile.png", ".doc"},
	{"assets/shellScript.png", ".sh"},
	{"assets/shellScript.png", ".bat"},
	{"assets/musicFile.png", ".wav"},
	{"assets/musicFile.png", ".ogg"},
	{"assets/musicFile.png", ".mp3"},
	{"assets/configFile.png", ".xml"},
	{"assets/configFile.png", ".ini"},
	{"assets/configFile.png", ".json"},
	{"assets/configFile.png", ".md"},
	{"assets/sourceFile.png", ".c"},
	{"assets/sourceFile.png", ".h"},
	{"assets/sourceFile.png", ".hpp"},
	{"assets/sourceFile.png", ".cpp"},
	{"assets/sourceFile.png", ".lua"},
	{"assets/sourceFile.png", ".java"},
	{"assets/sourceFile.png", ".py"},
	{"assets/sourceFile.png", ".asm"},
	{"assets/sourceFile.png", ".c"},
	{"assets/sourceFile.png", ".php"},
	{"assets/sourceFile.png", ".js"},
	{"assets/archive.png", ".rar"},
	{"assets/archive.png", ".zip"},
	{"assets/archive.png", ".7z"},
	{"assets/archive.png", ".tgz"},
	{"assets/archive.png", ".tar.gz"},
	{"assets/javaFile.png", ".class"},
	{"assets/javaFile.png", ".jar"},
	{"assets/binaryFile.png", ".exe"},
	{"assets/binaryFile.png", ".o"},
	{"assets/binaryFile.png", ".out"},
	{"assets/binaryFile.png", ".a"},
	{"assets/binaryFile.png", ".gch"},
	{"assets/binaryFile.png", ".dll"},
	{"assets/binaryFile.png", ".so"},
	{"assets/webFile.png", ".htm"},
	{"assets/webFile.png", ".html"},
	{"assets/webFile.png", ".css"},
	{"assets/fontsFile.png", ".ttf"},
	{"assets/fontsFile.png", ".otf"},
	{"assets/unknownFile.png", NULL},
};